%% Post https://studies.cs.helsinki.fi/exampleapp/new_note
sequenceDiagram
participant Browser
participant Sever

Browser ->> Sever : Post  https://studies.cs.helsinki.fi/exampleapp/new_note
Note over Browser,Sever: Sever add data from body of Post to data.json
Sever -->> Browser : responds status code 302 url redirect location /exampleapp/notes

Browser ->> Sever : Get https://studies.cs.helsinki.fi/exampleapp/notes
Sever -->> Browser : html document
Browser ->> Sever : Get https://studies.cs.helsinki.fi/exampleapp/main.css
Sever -->> Browser : The css file 
Browser ->> Sever : Get https://studies.cs.helsinki.fi/exampleapp/main.js
Sever -->> Browser : The javascript file 
Note over Browser,Sever: Browser execute javascript file and fetch data.json from Sever
Browser  ->> Sever: Get https://studies.cs.helsinki.fi/exampleapp/data.json
Sever -->> Browser: data.json file
Note over Browser,Sever: render data.json